[paths]
# Location of the raw datasets
IO_DATASETS = "/mnt/helios/osome/INCAS/infoops_new" # Location of pkl files
INCAS_DATASETS = "/mnt/helios/osome/INCAS/datasets" # Location of jsonl files

# Location where the preprocessed datasets will be stored
PREPROCESSED_DATASETS = "Data/Preprocessed"

#Logation of the outputs 
NETWORKS = "Outputs/Networks"
FIGURES = "Outputs/Figures"
TABLES = "Outputs/Tables"
CONFIGS = "Outputs/Configs"


# General settings for the null model
[nullmodel]
realizations = 0 # No nullmodel
scoreType = ["quantile"] #pvalue, 
batchSize = 10
idf = "smoothlog" # None, "none", "linear", "smoothlinear", "log", "smoothlog"
workers = -1 # Number of parallel workers. If -1, all the available cores will be used
minSimilarity = 0.0 # will only consider similarities above that value
# Specific settings for nullmodel of indicators
# will overwrite the general settings
# Example:
# [nullmodel.coretweet]
# minSimilarity = 0.4
#
# [nullmodel.cohashtag]
# idf = "smoothlinear"

# General settings for indicators
[indicator]
# total number of different items(left nodes) for that indicator
# e.g., minimum unique hashtags of the user
minUserDegree = 10
# total activity of the user for that indicator
# e.g., minimum uses of a user
minUserStrength = 1
# total number of different users(right nodes) for that indicator
# e.g., minimum unique users that used a hashtag
minItemDegree = 1
# total activity of the item for that indicator
# e.g., minimum uses of a hashtag
minItemStrength = 1
# min number of activities (among all indicators) of a user
minUserActivities = 10


# Thresholds for all the indicators
# Union approach uses different thresholds for each indicator
[indicator.coretweet.thresholds]
weight = 0.80
[indicator.cohashtag.thresholds]
weight = 0.80
[indicator.courl.thresholds]
weight = 0.80
[indicator.coword.thresholds]
weight = 0.85
[indicator.textsimilarity.thresholds]
weight = 0.85
[indicator.usctextsimilarity.thresholds]
weight = 0.85
# example to also include a threshold on similarity
# similarity = 0.5

# Specific settings for indicators
# will overwrite the general settings
# Example:
# [indicator.coretweet]
# minUserDegree = 20
# threshold = 0.05

[indicator.cohashtag]
minItemDegree = 1

[indicator.textsimilarity]
n_buckets = 5000
cache_path = "Data/Cache"



["merging"] 
#method used for merging the networks. Only pvalue or quantile are available for now
method = "max"
weightAttribute = "similarity" # Attribute to be used as weight for the merging
shouldAggregate = true

["community"]
detectCommunity = true
computeCommunityLabels = true
# Enable for computing the summarized labels of the communities

["output"]
thresholdAttribute = "similarity"
thresholds = [0]
# For union, thresholds should be [0] (no threshold)

# Specific extra thresholds for the output
# based on other features
# ["output.extraThresholds"]
# quantile = 0.0



