[paths]
EVALUATION_DATASETS = "/mnt/osome/Challenge2/Data/Preprocessed/"
IO_DATASETS = "/mnt/osome/INCAS/infoops_new"
INCAS_DATASETS = "/mnt/osome/INCAS/phase2b"
PREPROCESSED_DATASETS = "Data/Preprocessed"
NETWORKS = "Networks"
FIGURES = "Figures"

