[paths]
# Location of the raw datasets
IO_DATASETS = "/mnt/helios/osome/INCAS/infoops_new" # Location of pkl files
INCAS_DATASETS = "/mnt/helios/osome/INCAS/datasets" # Location of jsonl files

# Location where the preprocessed datasets will be stored
PREPROCESSED_DATASETS = "Data/Preprocessed"

#Logation of the outputs 
NETWORKS = "Outputs/Networks"
FIGURES = "Outputs/Figures"
TABLES = "Outputs/Tables"
CONFIGS = "Outputs/Configs"


# General settings for the null model
[nullmodel]
realizations = 0
scoreType = ["quantile"] # pvalue, 
batchSize = 10
idf = "smoothlog" # None, "none", "linear", "smoothlinear", "log", "smoothlog"
workers = -1 # Number of parallel workers. If -1, all the available cores will be used
minSimilarity = 0.2 # will only consider similarities above that
# Specific settings for nullmodel of indicators
# will overwrite the general settings
# Example:
# [nullmodel.coretweet]
# minSimilarity = 0.4
#
# [nullmodel.cohashtag]
# idf = "smoothlinear"

# General settings for indicators
[indicator]
# total number of different items(left nodes) for that indicator
# e.g., minimum unique hashtags of the user
minUserDegree = 10
# total activity of the user for that indicator
# e.g., minimum uses of a user
minUserStrength = 1
# total number of different users(right nodes) for that indicator
# e.g., minimum unique users that used a hashtag
minItemDegree = 1
# total activity of the item for that indicator
# e.g., minimum uses of a hashtag
minItemStrength = 1
# p-value threshold for the network
# pvalueThreshold = 0.01

[indicator.textsimilarity]
n_buckets = 5000
min_activity = 10
cache_path = "Data/Cache"

# Specific settings for indicators
# will overwrite the general settings
# Example:
# [indicator.coretweet]
# minUserDegree = 20
# pvalueThreshold = 0.05
#
# [indicator.cohashtag]
# minItemDegree = 5
# minItemStrength = 10

["merging"] 
method = "quantile" #method used for merging the networks. Only pvalue is available for now
shouldAggregate = true
weightAttribute = "quantile"
quantileThreshold = 0.0
pvalueThreshold = 1.0
similarityThreshold = 0.0

["output"]
thresholdAttribute = "quantile"
thresholds = [0.95,0.99,0.999,0.9999]

